name: build-tests
jobs:
  on: [ push, pull_request ]
  name: Test
  build:
    # Check if the PR is not from a fork
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        go: [ '1.15' ]
    name: Go ${{ matrix.go }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - run: go test -bench=  -race -test.v  ./...